# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
    role_hierarchy:
        ROLE_USER:   ROLE_USER
        ROLE_ADMIN: ROLE_ADMIN
        ROLE_RESPONSABLE_POLE: ROLE_RESPONSABLE_POLE
        ROLE_RESPONSABLE_CLUB: ROLE_RESPONSABLE_CLUB
        ROLE_MEMBRE_CLUB: ROLE_MEMBRE_CLUB

        # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username


    firewalls:
        main:
            pattern: ^/
            form_login:
                success_handler: authentication.handler.login_success_handler
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider

            logout:       true
            anonymous:    true
    access_control:
    - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin/, roles: [ROLE_ADMIN , ROLE_RESPONSABLE_POLE , ROLE_RESPONSABLE_CLUB]    }
    - { path: ^/client/, role: ROLE_USER }